---
- block:
  - name: install grafana
    ansible.builtin.apt:
      deb: "https://dl.grafana.com/oss/release/grafana_{{ grafana_version}}_amd64.deb"
  - name: enable grafana server service
    ansible.builtin.systemd:
      name: "grafana-server.service"
      enabled: yes
      state: restarted
  tags:
    - grafana
